import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="max-w-3xl p-4 mx-auto">
      <nav className='flex justify-between bg-sky-800 px-8 py-5 mx-auto my-5 text-white text-lg'>
        <Link className='' href="/">Go Coding</Link>
        <Link href="/addTopic" className='bg-white p-2 text-black'>Add Topic</Link>
    </nav>
      {children}</div>
        </body>
    </html>
  );
}
